# versions seem to all include "alpha", so I'm leaving that out. You may need to update the URL
#    below if the project stops including "alpha" on all releases.
{% set version = "0.1.23" %}

package:
  name: deno-dom
  version: {{ version }}

source:
  - url: https://github.com/b-fuze/deno-dom/archive/refs/tags/v{{ version }}-alpha.tar.gz
    sha256: 7dd25e6c9bda18905a084544684dc9edaf56edcc9b42089b652019e147599b04

build:
  number: 0

requirements:
  build:
    - {{ compiler("rust") }}
    - cargo-bundle-licenses
    - make   # [unix]
  run:
    - deno >=1.24.2

test:
  files:
    - test.ts
  commands:
    - if [ "$DENO_DOM_VERSION" != "{{ version }}-alpha" ]; then echo "DENO_DOM_VERSION not set correctly" && exit 1; fi             # [unix]

    - test -f $PREFIX/lib/deno_dom.so                        # [linux]
    - if [ "$DENO_DOM_PLUGIN" != "$PREFIX/lib/deno_dom.so" ]; then echo "DENO_DOM_PLUGIN var not set correctly" && exit 1; fi       # [linux]

    - test -f $PREFIX/lib/deno_dom.dylib                     # [osx]
    - if [ "$DENO_DOM_PLUGIN" != "$PREFIX/lib/deno_dom.dylib" ]; then echo "DENO_DOM_PLUGIN var not set correctly" && exit 1; fi    # [osx]

    - IF NOT EXIST %LIBRARY_LIB%\deno_dom.dll exit 1                              # [win]
    - IF "%DENO_DOM_PLUGIN:/=\%" NEQ "%LIBRARY_LIB%\deno_dom.dll" exit 1    # [win]
    - IF "%DENO_DOM_VERSION%" NEQ "{{ version }}-alpha" exit 1              # [win]

    # We can't run this test. The old deno_dom versions do not pin `plug`, and the API changed at some point.
    # error: Uncaught SyntaxError: The requested module 'https://deno.land/x/plug/mod.ts' does not provide an export named 'Plug'
    # import { Plug } from "https://deno.land/x/plug/mod.ts";
    # - deno run --unstable --allow-env --allow-ffi test_combined.ts

about:
  home: https://github.com/b-fuze/deno-dom
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - DENO_DOM_THIRDPARTY_LICENSES.yml
  summary: An implementation of the browser DOM—primarily for SSR—in Deno

extra:
  recipe-maintainers:
    - msarahan
